package com.community.community.mapper;

import com.community.community.entity.Comment;
import org.apache.ibatis.annotations.*;

import java.util.List;

@Mapper
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    Comment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    List<Comment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Comment record);

    @Select("select * From comment where parent_id = #{parentId}")
    List<Comment> selectByParentId(@Param("parentId") Integer parentId);

    @Select("select * From comment where parent_id = #{parentId} AND type=#{type} ORDER BY gmt_create desc")
    List<Comment> selectByParentIdAndType(@Param("parentId") Integer parentId,@Param("type") Integer type);

    @Select("select id From comment where parent_id = #{parentId} AND type=#{type}")
    List<Long> selectIdByParentIdAndType(@Param("parentId") Integer parentId,@Param("type") Integer type);

    @Delete("DELETE FROM COMMENT WHERE parent_id = #{parentId} AND type=#{type}")
    void deleteByParentIdAndType(@Param("parentId") Integer parentId,@Param("type") Integer type);

    @Update("UPDATE COMMENT SET comment_count = comment_count + 1 where id=#{id}")
    void incrCommentCount(@Param("id") Integer id);

    @Update("UPDATE COMMENT SET like_count = like_count + 1 where id=#{id} AND type = 1")
    void incrLikeCount(Integer id);
}