package com.community.community.mapper;

import com.community.community.entity.Comment;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

@Mapper
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    Comment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    List<Comment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Comment record);

    @Select("select * From comment where parent_id = #{id}")
    List<Comment> selectByParentId(@Param("id") Integer id);

    @Select("select * From comment where parent_id = #{id} AND type=#{type} ORDER BY gmt_create desc")
    List<Comment> selectByParentIdAndType(@Param("id") Integer id,@Param("type") Integer type);

    @Update("UPDATE COMMENT SET comment_count = comment_count + 1 where id=#{id}")
    void incrCommentCount(@Param("id") Integer id);

    @Update("UPDATE COMMENT SET like_count = like_count + 1 where id=#{id} AND type = 1")
    void incrLikeCount(Integer id);
}